### ISSUE TITLE
App crashes on back press, while gallery is loading

### ISSUE THREAD

**Issue by sheikh9871** [AnilFurkanOkcun/UWMediaPicker-Android#17]
java.lang.NullPointerException: lytProgressBar must not be null
        at com.anilokcun.uwmediapicker.ui.activity.UwMediaPickerDialogFragment$initPage$1.invokeSuspend(UwMediaPickerDialogFragment.kt:211)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by AnilFurkanOkcun** [comment]
Thank you for your feedback @sheikh9871. Fixed this at version 1.3.3. Also sorry for the late answer.
