### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by smoshie25** [AnilFurkanOkcun/UWMediaPicker-Android#3]
```
java.lang.NoSuchMethodError: No virtual method centerCrop()Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.biosec.youthparty-5b_4KGQPUQA-1eHncA-96g==/base.apk)
        at com.anilokcun.uwmediapicker.viewholder.GalleryMediaBucketVH.bind(GalleryMediaBucketVH.kt:38)
        at com.anilokcun.uwmediapicker.adapter.GalleryMediaRvAdapter.onBindViewHolder(GalleryMediaRvAdapter.kt:58)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7056)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7098)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6010)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6277)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6116)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6112)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4132)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3849)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4402)
        at android.view.View.layout(View.java:21352)
        at android.view.ViewGroup.layout(ViewGroup.java:6302)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:21352)
        at android.view.ViewGroup.layout(ViewGroup.java:6302)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:21352)
        at android.view.ViewGroup.layout(ViewGroup.java:6302)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:21352)
        at android.view.ViewGroup.layout(ViewGroup.java:6302)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:21352)
        at android.view.ViewGroup.layout(ViewGroup.java:6302)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:21352)
        at android.view.ViewGroup.layout(ViewGroup.java:6302)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:754)
        at android.view.View.layout(View.java:21352)
        at android.view.ViewGroup.layout(ViewGroup.java:6302)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2953)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2464)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1551)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7526)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1074)
E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:882)
        at android.view.Choreographer.doFrame(Choreographer.java:794)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1060)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6825)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by AnilFurkanOkcun** [comment]
Hi, thank you for your feedback. I couldn't reproduce it but I've updated some things. Can you try it with 1.1.0 version?

**Comment by smoshie25** [comment]
Thanks 
Another thing I want users to be able to select both videos and images the same time. how do I go about that

**Comment by AnilFurkanOkcun** [comment]
That feature is not available right now. But I took it as a feature request. I think the exception has been resolved. Thank you.

**Comment by AnilFurkanOkcun** [comment]
> Thanks
> Another thing I want users to be able to select both videos and images the same time. how do I go about that

I added that feature in version 1.2.0 :)
